[package]
name = "dmenu-launcher-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
dirs = "6.0.0"
serde = { version= "1.0.228", features = ["derive"] }
serde_yaml = "0.9.34"
clap = { version = "4.4", features = ["derive"] }
